// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvvWFn1jZhrGATpoBY56bJ7B486F48y0',
    appId: '1:616898823692:android:79be5594d594b5f1d8d029',
    messagingSenderId: '616898823692',
    projectId: 'project-aj-d0607',
    databaseURL: 'https://project-aj-d0607-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-aj-d0607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDcSoN6_8tY-VC4oLOT2WQyhJG2rDuJ0',
    appId: '1:616898823692:ios:4eab7e681c9187f8d8d029',
    messagingSenderId: '616898823692',
    projectId: 'project-aj-d0607',
    databaseURL: 'https://project-aj-d0607-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-aj-d0607.appspot.com',
    iosBundleId: 'com.example.projectAj',
  );
}
